In [1]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from bs4 import BeautifulSoup
from urllib.request import urlopen
from selenium.webdriver.common.keys import Keys
import time
import urllib.request
import pandas as pd
# import pymysql

In [2]:
df = pd.read_csv("./woman_all_info.csv")

In [3]:
df.head()

,0,1,2,3,4,5,6,7
0,아메카지,https://image.msscdn.net/images/style/detail/4...,1798977.0,3135345.0,3758440.0,3938742.0,3595140.0,2491355.0
1,아메카지,https://image.msscdn.net/images/style/detail/4...,3918784.0,3832752.0,3323776.0,3840727.0,3920478.0,NaN
2,아메카지,https://image.msscdn.net/images/style/detail/4...,3952906.0,3906923.0,3559898.0,3938962.0,2970072.0,3804473.0
3,아메카지,https://image.msscdn.net/images/style/detail/4...,1840202.0,2392496.0,3378574.0,2486339.0,NaN,NaN
4,아메카지,https://image.msscdn.net/images/style/detail/4...,3869943.0,3835564.0,3570874.0,3817805.0,3316179.0,3824474.0

In [4]:
ndf = df[["2", "3", "4", "5", "6", "7"]]
ndf.tail()

           2          3          4          5          6          7
0  1798977.0  3135345.0  3758440.0  3938742.0  3595140.0  2491355.0
1  3918784.0  3832752.0  3323776.0  3840727.0  3920478.0        NaN
2  3952906.0  3906923.0  3559898.0  3938962.0  2970072.0  3804473.0
3  1840202.0  2392496.0  3378574.0  2486339.0        NaN        NaN
4  3869943.0  3835564.0  3570874.0  3817805.0  3316179.0  3824474.0

In [ ]:
ndf.tail()

In [5]:
clothes_info = []
def clothes(id):
        # 옷 상세페이지 접속하기
        url = "https://www.musinsa.com/app/goods/"

        driver = webdriver.Chrome()
        
        try:
            driver.get(url + str(id)) # url 접속

            soup = BeautifulSoup(driver.page_source, "lxml")

            # 옷 종류 가져오기 
            category = soup.select("div a.product-detail__sc-up77yl-1")
            
            time.sleep(0.1)

            # 옷 이름 가져오기
            clothes_name = soup.find("h3", class_ = "product-detail__sc-1klhlce-3")
            
            time.sleep(0.1)

            # 옷 이미지
            images = soup.find("img", class_ = "product-detail__sc-p62agb-2")
            
            time.sleep(0.1)

            driver.close()

            # 가져온 옷 종류 리스트로 담기    
            clothes_list = []
            main_category = []
            sub_category = []

            # 옷 종류 추출하기
            for i in category:
                clothes_list.append(i.string)

            # 대분류 소분류 나누기
            for i in clothes_list:
                main_category.append(clothes_list[0]) 
                sub_category.append(clothes_list[1])

            print(clothes_list[0])
            print(clothes_list[1])

            # 옷 제목 추출하기
            clothes_title = []

            clothes_title.append(clothes_name.string)

            print(clothes_title[0])

            # 이미지 주소 

            image_urls = []
            image_urls.append(images.get("src"))
            print(image_urls[0])
            clothes_info.append([id, clothes_list[0], clothes_list[1],clothes_title[0], image_urls[0]])
        
        except:
            pass

In [6]:
# 데이터프레임과 내부에 들어있는 값 집어넣고 돌리면
# 해당 컬럼과 위치 알려줌

def find_value(df, value):
    result = df.applymap(lambda x: x == value)  # 각 요소가 찾는 값과 일치하는지 확인
    rows, cols = result.any(axis=1), result.any(axis=0)  # 행과 열 각각에 대해 True 값이 있는지 확인

    found_indices = []
    for row in df.index[rows]:  # True 값을 가진 행을 반복
        for col in df.columns[cols]:  # True 값을 가진 열을 반복
            if df.at[row, col] == value:  # 값이 일치하는지 다시 확인
                found_indices.append((row, col))

    return found_indices

find_value(ndf,1375408.0)

[(3482, '4'), (7183, '3'), (8149, '3'), (15035, '2')]

# 데이터 수집

In [ ]:
# 오래 걸리니 컴퓨터 나눠서 돌리기 
# ndf 컬럼명, 2번째 for문 range값만 수정해서 돌리기
a = []

for i in ndf[["2"]]: # 2번 컬럼만 수집
    q = ndf[i]
    
    for j in range(15035, 15934): # 끊긴 인덱스부터 끝까지
        o = q[j]
        
        try:
            w = int(o)

            if w not in a:
                a.append(w)

        except:
            pass

        
for id in a:
    clothes(id)

여성 가방
숄더백
RAINBOW HOBO blue
https://image.msscdn.net/images/goods_img/20200331/1375408/1375408_1_500.jpg
바지
데님 팬츠
Slim cutting pants
https://image.msscdn.net/images/goods_img/20200401/1378262/1378262_1_500.jpg
원피스
미니 원피스
프릴 미니 드레스 (아이보리)_S
https://image.msscdn.net/images/goods_img/20200520/1455772/1455772_16970060951176_500.jpg
여성 가방
숄더백
브로드백 - 페일스톤
https://image.msscdn.net/images/goods_img/20200316/1353177/1353177_2_500.jpg
상의
셔츠/블라우스
실키 백리스 탑 블루 그린
https://image.msscdn.net/images/goods_img/20191020/1194603/1194603_1_500.jpg
스커트
미디스커트
Wrinkle Skirt - Ivory
https://image.msscdn.net/images/goods_img/20200603/1473021/1473021_1_500.jpg
상의
민소매 티셔츠
셔링 슬리브리스 탑_스카이 블루
https://image.msscdn.net/images/goods_img/20200630/1501530/1501530_1_500.jpg
여성 가방
토트백
청키 체리 니트 백
https://image.msscdn.net/images/goods_img/20170903/623339/623339_1_500.jpg
아우터
카디건
NOI093 썸머 니트 가디건 (옐로우)
https://image.msscdn.net/images/goods_img/20200713/1513846/1513846_1_500.jpg
여성 가방
숄더백
Pumpkin Bag (Ivory)
https://image.msscdn.net/images/goods_img/20200330/1373624/1373624_1_500.jpg
여성 가방
숄더백
Pitta PVC White
https://image.msscdn.net/images/goods_img/20200414/1405215/1405215_1_500.jpg
신발
샌들
Brooklyn White
https://image.msscdn.net/images/goods_img/20200624/1496195/1496195_1_500.jpg
신발
샌들
Emma Black
https://image.msscdn.net/images/goods_img/20200410/1397886/1397886_1_500.jpg
여성 가방
숄더백
Pitta Green
https://image.msscdn.net/images/goods_img/20200414/1405216/1405216_1_500.jpg
원피스
맥시 원피스
플루이드 원피스 [지브라]
https://image.msscdn.net/images/goods_img/20200617/1488405/1488405_1_500.jpg
상의
반소매 티셔츠
BASIC T-SHIRTS WHITE
https://image.msscdn.net/images/goods_img/20190415/1014752/1014752_1_500.jpg
주얼리
반지
시엔나 더블 반지
https://image.msscdn.net/images/goods_img/20200420/1412131/1412131_1_500.jpg
주얼리
귀걸이
번트 귀걸이 E1
https://image.msscdn.net/images/goods_img/20200420/1410879/1410879_1_500.jpg
원피스
미디 원피스
A FLOWER BUTTON STRIPE DR
https://image.msscdn.net/images/goods_img/20200520/1455665/1455665_1_500.jpg
원피스
미니 원피스
FLOWER SHIRRING DRESS - BEIGE
https://image.msscdn.net/images/goods_img/20200507/1434821/1434821_4_500.jpg
주얼리
목걸이/펜던트
clova honey pearl necklace
https://image.msscdn.net/images/goods_img/20200625/1497798/1497798_1_500.jpg
주얼리
팔찌
하트 스톤 체인 팔찌
https://image.msscdn.net/images/goods_img/20200420/1410883/1410883_2_500.jpg
상의
셔츠/블라우스
LACE RUFFLE SLEEVELESS BLOUSE - WHITE
https://image.msscdn.net/images/goods_img/20200512/1441612/1441612_1_500.jpg
여성 가방
숄더백
Hera Ivory
https://image.msscdn.net/images/goods_img/20200520/1455546/1455546_6_500.jpg
상의
셔츠/블라우스
(BL-20323) LACE OFF-SHOULDER FRILL SHIRT WHITE
https://image.msscdn.net/images/goods_img/20200527/1465383/1465383_2_500.jpg
상의
셔츠/블라우스
LACE RUFFLE SLEEVELESS BLOUSE - YELLOW
https://image.msscdn.net/images/goods_img/20200512/1441592/1441592_1_500.jpg
원피스
미디 원피스
더블 스트링 드레스 -그린
https://image.msscdn.net/images/goods_img/20200520/1455175/1455175_1_500.jpg
원피스
맥시 원피스
Puff Sleeve Line dress - Lilac
https://image.msscdn.net/images/goods_img/20200603/1473117/1473117_1_500.jpg
주얼리
귀걸이
ACL ROUND EARRING (2 COLOR)
https://image.msscdn.net/images/goods_img/20200619/1490907/1490907_1_500.jpg
주얼리
목걸이/펜던트
[SILVER] WH TAIL P NECKLACE
https://image.msscdn.net/images/goods_img/20200619/1490853/1490853_1_500.jpg
상의
셔츠/블라우스
프릴 리본 블라우스 옐로베이지
https://image.msscdn.net/images/goods_img/20200609/1477408/1477408_1_500.jpg
주얼리
귀걸이
[SILVER] MIX BALL R EARRING (2 COLOR)
https://image.msscdn.net/images/goods_img/20200619/1490887/1490887_1_500.jpg
원피스
맥시 원피스
뽀삐 세일러 드레스
https://image.msscdn.net/images/goods_img/20200611/1482534/1482534_2_500.jpg
원피스
미니 원피스
Puffy Strappy Embroidered Dress 2
https://image.msscdn.net/images/goods_img/20200610/1479777/1479777_1_500.jpg
원피스
맥시 원피스
Sailor Gingham Dress (Olive Green)
https://image.msscdn.net/images/goods_img/20200610/1479783/1479783_1_500.jpg
원피스
맥시 원피스
투 플로어즈 드레스/피치
https://image.msscdn.net/images/goods_img/20200611/1482533/1482533_1_500.jpg
아우터
슈트/블레이저 재킷
20SS 썸머 울 스트라이프 자켓
https://image.msscdn.net/images/goods_img/20200604/1473931/1473931_2_500.jpg
원피스
맥시 원피스
Wrap Flared Dress - Red
https://image.msscdn.net/images/goods_img/20200603/1473084/1473084_1_500.jpg
원피스
맥시 원피스
Floral Linen V-Neck Dress (Ivory)
https://image.msscdn.net/images/goods_img/20200610/1479791/1479791_1_500.jpg
신발
슬리퍼
michelle flipflop - ivory
https://image.msscdn.net/images/goods_img/20200509/1438089/1438089_1_500.jpg
상의
셔츠/블라우스
Ribbon Collar Blouse
https://image.msscdn.net/images/goods_img/20200610/1479775/1479775_1_500.jpg
상의
니트/스웨터
네트 패턴 니트 탑 [아이보리]
https://image.msscdn.net/images/goods_img/20200523/1459803/1459803_1_500.jpg
원피스
미니 원피스
Floral Double Button Collar Dress (Light Purple)
https://image.msscdn.net/images/goods_img/20200610/1479790/1479790_1_500.jpg
주얼리
귀걸이
pearl rosa drop earring
https://image.msscdn.net/images/goods_img/20200413/1402025/1402025_1_500.jpg
주얼리
귀걸이
FruiitFruiit pearl earring [Silver925]
https://image.msscdn.net/images/goods_img/20200226/1324723/1324723_1_500.jpg
주얼리
귀걸이
Emerald paerl earring [4floor]
https://image.msscdn.net/images/goods_img/20200226/1324720/1324720_1_500.jpg
여성 가방
숄더백
Allure Black 알뤼르 블랙
https://image.msscdn.net/images/goods_img/20200513/1443845/1443845_1_500.jpg
주얼리
귀걸이
Baroque pearl holiday earring
https://image.msscdn.net/images/goods_img/20200226/1324863/1324863_2_500.jpg
주얼리
목걸이/펜던트
담수진주 목걸이
https://image.msscdn.net/images/goods_img/20200609/1478287/1478287_1_500.jpg
신발
블로퍼
IS_201091IV
https://image.msscdn.net/images/goods_img/20200224/1319101/1319101_1_500.jpg
원피스
미디 원피스
Ribbon Point Midi Dress_ Yellow
https://image.msscdn.net/images/goods_img/20200521/1456520/1456520_1_500.jpg
여성 가방
숄더백
아멜리아 프레임 백_실버
https://image.msscdn.net/images/goods_img/20200219/1312541/1312541_3_500.jpg
바지
트레이닝/조거 팬츠
RIVET WIDE PANTS (CREAM)
https://image.msscdn.net/images/goods_img/20200407/1388901/1388901_1_500.jpg
바지
숏 팬츠
[DANA 8112]베이직워싱 슬림핏 숏쇼츠 데님(연청/진청)
https://image.msscdn.net/images/goods_img/20200508/1437765/1437765_1_500.jpg
주얼리
귀걸이
twist layered unbal earring
https://image.msscdn.net/images/goods_img/20200226/1323656/1323656_1_500.jpg
원피스
미니 원피스
Unbalance Mini Dress_ Black
https://image.msscdn.net/images/goods_img/20200303/1332319/1332319_1_500.jpg
주얼리
귀걸이
matt bar layerd unbal earring
https://image.msscdn.net/images/goods_img/20200226/1324021/1324021_2_500.jpg
주얼리
귀걸이
Star of the Sea
https://image.msscdn.net/images/goods_img/20200429/1428317/1428317_1_500.jpg
상의
셔츠/블라우스
코르셋 크롭 블라우스 (화이트)
https://image.msscdn.net/images/goods_img/20200520/1455701/1455701_16956181691573_500.jpg
바지
데님 팬츠
Straight 02 - Ivory
https://image.msscdn.net/images/goods_img/20200312/1347641/1347641_2_500.jpg
여성 가방
숄더백
나나백_체크
https://image.msscdn.net/images/goods_img/20190205/947818/947818_3_500.jpg
주얼리
귀걸이
Oval Chain - leopard
https://image.msscdn.net/images/goods_img/20200429/1428249/1428249_1_500.jpg
바지
숏 팬츠
[DANA 8121]커버밴드 베이직 A라인핏 4부 쇼츠 코튼 팬츠(아이보리)
https://image.msscdn.net/images/goods_img/20200508/1437771/1437771_1_500.jpg

In [ ]:
# 수집된 데이터 프레임으로 변환
# 중간에 끊을때는 꼭 저장하기

all_clothes_info = pd.DataFrame(clothes_info)
all_clothes_info.head()

In [ ]:
all_clothes_info.to_csv("./data/women_model_item_2(15035_).csv", index = False)

In [33]:
# 마지막에 끊긴거 몇번째 인덱스 인지 찾기
find_value(ndf, 4006800.0)

C:\Users\ITSC\AppData\Local\Temp\ipykernel_18616\895915479.py:5: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  result = df.applymap(lambda x: x == value)  # 각 요소가 찾는 값과 일치하는지 확인

[(11, '2'), (13, '7')]